# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affichage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlchemyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='googleresult',
            name='mathieu',
        ),
        migrations.AlterField(
            model_name='googleresult',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affichage.Query'),
        ),
        migrations.AddField(
            model_name='alchemyresult',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affichage.Query'),
        ),
    ]
