# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affichage', '0002_auto_20170103_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tout', models.TextField()),
                ('cover', models.TextField()),
                ('partition', models.TextField()),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='affichage.Query')),
            ],
        ),
        migrations.AlterField(
            model_name='alchemyresult',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='affichage.Query'),
        ),
        migrations.AlterField(
            model_name='googleresult',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='affichage.Query'),
        ),
    ]
